int perimetro, area, pote, pote1;
Console.WriteLine("Escriba la altura de un rectangulo");
int altura = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Escriba el ancho de un rectangulo");
int ancho = Convert.ToInt32(Console.ReadLine());
area = altura * ancho;
perimetro = 2 * (ancho + altura);
pote = ancho * ancho;
pote1 = altura * altura;
double pote2 = pote + pote1;
double diagonal = Math.Sqrt(pote2);
Console.WriteLine("El area del rectangulo es " + area);
Console.WriteLine("El perimetro del rectangulo es " + perimetro);
Console.WriteLine("La diagonal del rectangulo es " + diagonal);
Console.ReadKey();